In [41]:
import json
import requests
import spacy
import nltk
from collections import Counter
import sys
import numpy as np
sys.path.append("..")
from crowdrank import interpreter

from spacy.lang.en.stop_words import STOP_WORDS

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
cmt_path = '/Users/luc.dhauthuille/Desktop/insightAI/data/interpreted_data/headphoneadvice_360.json'

In [5]:
cmts_upvotes = interpreter.get_local('headphoneadvice')

In [7]:
len(cmts_upvotes)

5046

In [ ]:
# Testing this on a general corpus


In [8]:
# Corpus:
corpus = [c[0] for c in cmts_upvotes]

In [91]:
vectorizer = TfidfVectorizer(stop_words = 'english')
X = vectorizer.fit_transform(corpus)

In [92]:
names = vectorizer.get_feature_names()

In [94]:
print(X.shape)

(5046, 10498)


In [93]:
print(X[0])

  (0, 6331)	0.5966520938901931
  (0, 4829)	0.5966520938901931
  (0, 10414)	0.5366680144306126


In [66]:
names[6377]

'mx3'

In [67]:
print(corpus[2])

The ATH-A990z might work for you if you don't need huge bass.  Good for gaming.


In [68]:
print(X[2])

  (0, 4259)	0.2682356550536145
  (0, 4380)	0.19641141435637607
  (0, 1578)	0.23634484050223256
  (0, 4848)	0.4065476424704948
  (0, 6435)	0.27036756121903877
  (0, 3256)	0.21886007998140844
  (0, 10301)	0.3020413729693875
  (0, 775)	0.5716825428620484
  (0, 1303)	0.35956090842956456


In [84]:
x_arr = X.toarray()

In [73]:
x_arr.shape


(5046, 10781)

In [76]:
x_arr.sum(axis=0)

array([1.50556617, 1.00478277, 0.39691569, ..., 0.37332956, 0.37332956,
       0.37332956])

In [40]:
print(names[10692])

yamaha


In [44]:
#arr.argsort()[-3:][::-1]
x_arr[0].argsort()[-3:]

array([10692,  6477,  4947])

In [46]:
x_arr[1].argsort()[-5:]

array([8867, 5211, 3706, 7401, 9587])

In [53]:
names[8867]

'soon'

In [48]:
print(corpus[1])

These look fantastic. Reviews seem to be almost entirely positive too. As soon as I find some information on the soundstage I may have to pick these up.

Thanks!


In [80]:
word_index = vectorizer.vocabulary_

In [81]:
index_to_word = {i: w for w, i in word_index.items()}

In [82]:
print(len(index_to_word))

10498


In [147]:
# for each comment in corpus, what is the top-10 most important words:
for i, c in enumerate(corpus):
    print(c)
    print([index_to_word[j] for j in x_arr[i].argsort()[-10:]])
    if i > 9 :
        break

Yamaha HPH MT8
['efficency', 'efficiency', 'efficient', 'effort', 'effortlessly', 'effects', '𝘪𝘯', 'yamaha', 'hph', 'mt8']
These look fantastic. Reviews seem to be almost entirely positive too. As soon as I find some information on the soundstage I may have to pick these up.

Thanks!
['look', 'thanks', 'soundstage', 'reviews', 'fantastic', 'pick', 'soon', 'information', 'entirely', 'positive']
The ATH-A990z might work for you if you don't need huge bass.  Good for gaming.
['effed', 'good', 'don', 'bass', 'gaming', 'need', 'work', 'ath', 'huge', 'a990z']
Yeah I’ll have to check those out. I bought the A550Z’s recently but can’t help but feel like I’m missing out on something. I’m looking to really experience music like I’m *apparently* meant to.
['check', 'feel', 'help', 'bought', 'like', 'recently', 'meant', 'apparently', 'missing', 'a550z']
I use the AKG K553 in the office everyday.  I think they are very good if you can get them around $150.  The new Mk II version has removeable cabl

In [61]:
# includes stop_words
print(len(index_to_word))

10781


In [104]:
brands = []
with open('../data/product_data/brands.txt') as f:
    for l in f:
        brands.append(l.rstrip())

In [105]:
brands

['sanus',
 'boytone',
 'denaq',
 'dreamwave',
 'yamaha',
 'universal remote control',
 'bose',
 'samsung',
 'corsair',
 'outdoor tech',
 'motorola',
 'wd',
 'panamax',
 'alpine',
 'transcend',
 'mee audio',
 'speakercraft',
 'peerless',
 'kenwood',
 'microsoft',
 'ultimate ears',
 'niles',
 'peak design',
 'lowepro',
 'sdi technologies, inc.',
 'polk audio',
 'apple',
 'peerless-av',
 'denon',
 'lenovo',
 'elite screens',
 'sony',
 'russound',
 'svs',
 'hisense',
 'house of marley',
 'midland',
 'marantz',
 'jvc',
 'isimple',
 'chief',
 'turtle beach',
 'audioquest',
 'toshiba',
 'logitech',
 'siriusxm',
 'pny',
 'jbl',
 'kicker',
 'kanto living',
 'mtx',
 'sling media',
 'power acoustik',
 'sandisk',
 'novatel',
 'skullcandy',
 'asus',
 'martinlogan',
 'pioneer',
 'belkin',
 'vinpower digital directship',
 'dell',
 'pelican',
 'razer',
 'alienware',
 'canon',
 'sharp',
 'olympus',
 'house of marley',
 'netgear',
 'hoya',
 'tp-link',
 'digipower',
 'corsair',
 'onkyo',
 'definitive tec

In [106]:
from spacy.tokenizer import Tokenizer

In [125]:
# Construction 2 (SpaCy.io)
from spacy.lang.en import English
nlp = English()
# Create a Tokenizer with the default settings for English
# including punctuation and exceptions
tokenizer = nlp.Defaults.create_tokenizer(nlp)

In [126]:
tokens = tokenizer("Yo can you tokenize something if Bose's it doesn't deserve it?")

In [127]:
type(tokens)

spacy.tokens.doc.Doc

In [128]:
print(["{}".format(t) for t in tokens])

['Yo', 'can', 'you', 'tokenize', 'something', 'if', 'Bose', "'s", 'it', 'does', "n't", 'deserve', 'it', '?']


In [139]:
# Convert to strings
tokens_list = [t.orth_ for t in tokens]

In [129]:
token_set = set(tokens)

In [142]:
token_set

{Yo,
 can,
 you,
 tokenize,
 something,
 if,
 Bose,
 's,
 it,
 does,
 n't,
 deserve,
 it,
 ?}

In [131]:
'can' in token_set

False

In [144]:
'can' in list(tokens)

str

In [ ]:
# Almost done:

# Get entity: [comments] maps,
# Run TF-IDF on this where groups of comments are "documents"